version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools --version 4.0.0
      - PATH="$PATH:/root/.dotnet/tools"
  pre_build:
    commands:
      - echo "ProjectPath $ProjectPath"
      - echo "Framework $Framework"
      - echo "Configuration $Configuration"
      - echo "ArtifactBucket $ArtifactBucket"
      - echo "ArtifactBucketPrefix $ArtifactBucketPrefix"
      - echo "TemplateFileName $TemplateFileName"
      - echo "OutputTemplateFileName $OutputTemplateFileName"
      - cd $ProjectPath
  build:
    commands:
      - >
         dotnet lambda package-ci
         --framework $Framework
         --configuration $Configuration
         --template $TemplateFileName
         --output-template bin/$OutputTemplateFileName
         --s3-bucket $ArtifactBucket
         --s3-prefix $ArtifactBucketPrefix/
artifacts:
  base-directory: $ProjectPath
  files:
    - bin/$OutputTemplateFileName
  discard-paths: yes
