version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - dotnet tool install -g Amazon.Lambda.Tools --version 4.0.0
      # see https://github.com/dotnet/sdk/issues/9304#issuecomment-401670622
      - echo "$(dirname $(realpath $(which dotnet)))"
      - export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))
  pre_build:
    commands:
      - echo "ProjectPath $ProjectPath"
      - echo "Framework $Framework"
      - echo "Configuration $Configuration"
      - echo "ArtifactBucket $ArtifactBucket"
      - echo "ArtifactBucketPrefix $ArtifactBucketPrefix"
      - echo "TemplateFileName $TemplateFileName"
      - echo "OutputTemplateFileName $OutputTemplateFileName"
      - cd $ProjectPath
  build:
    commands:
      - >
         dotnet lambda package-ci
         --framework $Framework
         --configuration $Configuration
         --template $TemplateFileName
         --output-template bin/$OutputTemplateFileName
         --s3-bucket $ArtifactBucket
         --s3-prefix $ArtifactBucketPrefix/
         --msbuild-parameters "/p:PublishReadyToRun=true --self-contained false"
artifacts:
  base-directory: $ProjectPath
  files:
    - bin/$OutputTemplateFileName
  discard-paths: yes
